/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import java.util.ArrayList;
import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        ArrayList<Integer> list = new ArrayList<>();
        for(int i=0; i<10;i++){
            list.add (0); 
        }
        Scanner s = new Scanner(System.in);
        System.out.println("Sirasiyla firstIndex[0-9], lastINdex[0-9] ve eklenecek sayiyi girin");
        int first = s.nextInt();
        int last = s.nextInt();
        int add = s.nextInt();
        addValToRange(list, first, last, add);
        System.out.println("Sonuc:");
        for(int i=0; i<list.size(); i++){
            System.out.println(list.get(i));
        }
                
    }



    public static void addValToRange(ArrayList<Integer> list, Integer first, Integer last, Integer val){
        
        if(first < 0 || last < 0 || last < first || list == null || first >= list.size() || last >= list.size()){
            System.out.println("Yanlis input girildi!");
            throw new IllegalArgumentException();
        }
        for (int i=first; i<=last; i++){
            list.set(i, list.get(i)+val);
        }
    }
}
